spring:
  application:
    name: crawler-service
  datasource:
    url: jdbc:mysql://mysql-container:3306/hust_assistant_data?useUnicode=true&characterEncoding=utf8mb4&serverTimeZone=UTC
    username: root
    password: root
